"""Word Assembler — Step ⑧ for the report skill.

In the architecture doc (§5.3.3) this role is played by DocumentFormat.OpenXml in C#.
Here we use python-docx for a pure-Python equivalent.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

from docx import Document
from docx.shared import Pt, RGBColor

OUTPUT_DIR = Path(__file__).parent.parent / "outputs"


def build_word_report(content: dict[str, Any]) -> str:
    """Build a real .docx file from a structured content dict.

    Expected shape (matches the JSON Schema used by report skill):
        {
            "title": "...",
            "subtitle": "...",
            "executive_summary": "...",
            "sections": [
                {"heading": "...", "paragraphs": ["...", "..."]},
                {"heading": "...", "table": {"headers": [...], "rows": [[...]]}},
            ],
            "conclusion": "..."
        }

    Returns the path of the generated file (relative to the project root).
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    doc = Document()

    # Title
    title = content.get("title", "SDS Lite Report")
    title_para = doc.add_heading(title, level=0)
    title_para.runs[0].font.color.rgb = RGBColor(0x1F, 0x4E, 0x79)

    # Subtitle
    if subtitle := content.get("subtitle"):
        sub = doc.add_paragraph(subtitle)
        sub.runs[0].italic = True
        sub.runs[0].font.size = Pt(11)

    # Metadata line
    meta = doc.add_paragraph(
        f"Generated by Skill Router AI · {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    meta.runs[0].font.size = Pt(9)
    meta.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    # Executive summary
    if exec_summary := content.get("executive_summary"):
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(exec_summary)

    # Sections
    for section in content.get("sections", []):
        doc.add_heading(section.get("heading", "Section"), level=1)
        for paragraph in section.get("paragraphs", []):
            doc.add_paragraph(paragraph)
        if table_def := section.get("table"):
            _add_table(doc, table_def)

    # Conclusion
    if conclusion := content.get("conclusion"):
        doc.add_heading("Conclusion", level=1)
        doc.add_paragraph(conclusion)

    # Write file
    safe_title = "".join(c if c.isalnum() else "_" for c in title)[:50]
    filename = f"{safe_title}_{uuid.uuid4().hex[:8]}.docx"
    out_path = OUTPUT_DIR / filename
    doc.save(out_path)
    return str(out_path.relative_to(OUTPUT_DIR.parent))


def _add_table(doc: Document, table_def: dict) -> None:
    headers = table_def.get("headers", [])
    rows = table_def.get("rows", [])
    if not headers:
        return
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    header_cells = table.rows[0].cells
    for i, h in enumerate(headers):
        header_cells[i].text = str(h)
        header_cells[i].paragraphs[0].runs[0].bold = True
    for row in rows:
        cells = table.add_row().cells
        for i, value in enumerate(row):
            if i < len(headers):
                cells[i].text = str(value)
